### ISSUE TITLE
Review sytem dependencies

### ISSUE THREAD

**Issue by gforcada** [plone/plone.jenkins_server#13]
Currently this ansible role installs quite a few system dependencies, see https://github.com/plone/plone.jenkins_server/blob/master/defaults/main.yml#L14

Quite a few of them are related to running jenkins jobs on it, but as we run them on nodes (see https://github.com/plone/plone.jenkins_node ansible role), does make sense to keep all these dependencies on the server also?

Or to put it in another way: *is master supposed to be running jenkins jobs?*

If yes we most probably need to copy plone.jenkins_node dependencies then as we are missing quite a few (https://github.com/plone/plone.jenkins_node/blob/master/tasks/main.yml#L15)

**Comment by tisto** [comment]
No. Master is not supposed to run jenkins jobs. People can install both master and node ansible playbooks if they want to run it all on one machine. Therefore we can remove those dependencies.

**Comment by gforcada** [comment]
Perfect, removed them then.
