### ISSUE TITLE
Release to ansible galaxy

### ISSUE THREAD

**Issue by gforcada** [plone/plone.jenkins_server#14]
It's about time to release the role into the wild, right?

It would be nice to just use:

```
ansible-galaxy install plone.jenkins_server
```

Instead of having to keep the git submodule on jenkins.plone.org.

Still before that I would say that at least we need to make the GitHub integration and the mr.roboto integration optional.

Then, once that's optional the role as it is would it be useful for third parties outside jenkins.plone.org.

Ideas, comments?

**Comment by tisto** [comment]
+1

**Comment by gforcada** [comment]
ansible-jenkins just got released: https://github.com/ICTO/ansible-jenkins/issues/25 :) one less blocker for it :)

**Comment by gforcada** [comment]
Done
