### ISSUE TITLE
The README does not state how to set variables.

### ISSUE THREAD

**Issue by tisto** [plone/plone.jenkins_server#5]
@svx: I tried to install the github plugin with this line:

- { role: plone.jenkins_server, jenkins_plugins: 'github' }

I also tried some other approaches, but none of the made "vagrant provision" install the plugin. The playbook always just installes the greenballs plugin. We should include some instructions in the README for this.

**Comment by gforcada** [comment]
I think this is largely solved by now, right?

Well, actually we are still hard-coding plugins list, but now on ``metadata/main.yml`` as we are relying on ansible-jenkins role...
